#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

# Install Nginx
apt-get update
apt-get install -y nginx

# Creating Sample Page
echo "Hello World!" > /var/www/html/index.html

# add the following configuration to the existing server block
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

echo -e "Ceci n'est pas une page" > /etc/nginx/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/etc\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Add custom HTTP response header
echo "add_header X-Served-By \$hostname;" >> /etc/nginx/nginx.conf

# Restart Nginx
service nginx restart

