#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

# Install HAProxy
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
apt-get -y update
apt-get install -y haproxy

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
frontend http-in
    bind *:80
    mode http
    default_backend servers

backend servers
    mode http
    balance roundrobin
    server web-01 154258-web-01 54.197.83.147:80 check
    server web-02 154258-web-02 100.26.10.83:80 check
EOF

# Enable HAProxy init script
sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# Restart HAProxy
service haproxy restart
