#!/usr/bin/env bash
#Script that displays the content of the file /etc/passwd


# set the input field separator to colon
IFS=":"

# read the /etc/passwd file line by line
while read -r username password userid groupid user_info homedir shell; do
  # extract the relevant fields and display them
  echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
