#!/usr/bin/env bash
# Creates an RSA and password key pair
#ssh-keygen -t rsa -f school -b 4096 -N betty

# Generate a 4096-bit RSA key pair with a passphrase
openssl genrsa -aes256 -out school.key 4096

# Extract the public key from the generated key pair
openssl rsa -in school.key -out school.pub -outform PEM -pubout

echo "RSA key pair has been created with the name 'school.key' and passphrase 'betty'."
